import { Product, Category, Collection, Review, Coupon, ShippingMethodOption, Order, User, BespokeInquiry, Conversation, AtelierStaff } from '../types';
import { ARMORED_SHIPPING_METHODS } from '../internationalConfig';

export const mockCategories: Category[] = [
  {
    id: 'cat-rings',
    name: 'Rings',
    slug: 'rings',
    description: 'GIA certified solitaires, pavé eternity bands, and sculptural cocktail rings handcrafted in 18K and 22K gold.',
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1000&q=80',
    itemCount: 24,
  },
  {
    id: 'cat-necklaces',
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'High jewellery diamond collars, graduated tennis necklaces, and bespoke Colombian emerald chokers.',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=80',
    itemCount: 18,
  },
  {
    id: 'cat-earrings',
    name: 'Earrings',
    slug: 'earrings',
    description: 'Brilliant cut diamond studs, celestial chandeliers, and cascading emerald drops.',
    imageUrl: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1000&q=80',
    itemCount: 16,
  },
  {
    id: 'cat-bracelets',
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Iconic tennis bracelets, diamond line cuffs, and flexible gold link creations.',
    imageUrl: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1000&q=80',
    itemCount: 14,
  },
  {
    id: 'cat-bangles',
    name: 'Bangles',
    slug: 'bangles',
    description: 'Solid 18K & 22K gold rigid bangles with intricate filigree and hidden diamond hinges.',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1000&q=80',
    itemCount: 12,
  },
  {
    id: 'cat-pendants',
    name: 'Pendants',
    slug: 'pendants',
    description: 'Symbolic talismans, bezel-set certified solitaires, and architectural medallions.',
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1000&q=80',
    itemCount: 15,
  },
  {
    id: 'cat-chains',
    name: 'Chains',
    slug: 'chains',
    description: 'Heavy curb, wheat, rope, and box chains hand-spun in solid 18K yellow and rose gold.',
    imageUrl: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1000&q=80',
    itemCount: 9,
  },
  {
    id: 'cat-mens',
    name: "Men's Jewellery",
    slug: 'mens-jewellery',
    description: 'Architectural signet rings, solid platinum cuff links, and heavy diamond link bands for discerning gentlemen.',
    imageUrl: 'https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?auto=format&fit=crop&w=1000&q=80',
    itemCount: 11,
  },
  {
    id: 'cat-womens',
    name: "Women's Jewellery",
    slug: 'womens-jewellery',
    description: 'Elegantly proportioned feminine creations capturing eternal light and effortless refinement.',
    imageUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=80',
    itemCount: 42,
  },
  {
    id: 'cat-custom',
    name: 'Custom Jewellery',
    slug: 'custom-jewellery',
    description: 'Bespoke commissions designed alongside our Master Gemologists and Parisian craftsmen.',
    imageUrl: 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?auto=format&fit=crop&w=1000&q=80',
    itemCount: 6,
  },
];

export const mockCollections: Collection[] = [
  {
    id: 'col-solitaire-masterpieces',
    name: 'Solitaire Masterpieces',
    slug: 'solitaire-masterpieces',
    subtitle: 'GIA Graded Solitaires of Rare Radiance',
    description: 'Each solitaire is hand-selected for exceptional cut symmetry, pristine F-IF clarity, and fiery dispersion.',
    bannerImage: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1600&q=85',
    isFeatured: true,
  },
  {
    id: 'col-royal-emerald',
    name: 'The Royal Emerald Collection',
    slug: 'royal-emerald',
    subtitle: 'Verdant Treasures from Muzo & Chivor',
    description: 'Untreated Colombian emeralds paired with high-clarity diamond clusters, hand-set in 18K solid gold.',
    bannerImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1600&q=85',
    isFeatured: true,
  },
  {
    id: 'col-vendome-high-jewellery',
    name: 'Place Vendôme Heritage',
    slug: 'vendome-heritage',
    subtitle: 'Parisian Architectural Haute Joaillerie',
    description: 'Honoring four generations of classical French jewellery craftsmanship with articulated gold work.',
    bannerImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1600&q=85',
    isFeatured: true,
  },
  {
    id: 'col-luminary-diamonds',
    name: 'Luminary Diamond Line',
    slug: 'luminary-diamonds',
    subtitle: 'Pure Flawless Diamond River Creations',
    description: 'Perfect matching tennis bracelets, line collars, and studs displaying optical symmetry.',
    bannerImage: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1600&q=85',
    isFeatured: false,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-01',
    name: 'L’Éternité Oval Diamond Solitaire Ring',
    slug: 'leternite-oval-diamond-solitaire-ring',
    sku: 'AUR-RNG-001',
    brand: 'Maison Aurelia',
    category: 'Rings',
    subcategory: 'Solitaire Engagement Rings',
    collection: 'Solitaire Masterpieces',
    gender: 'Women',
    shortDescription: 'A 2.50ct oval brilliant natural diamond set upon a knife-edge band of 18K gold with hidden diamond gallery.',
    description: 'The L’Éternité Solitaire represents the pinnacle of modern classicism. Hand-forged in our Paris Place Vendôme atelier, this ring features an exceptional oval-cut diamond (E Color, VVS1 Clarity, GIA Certified) floating effortlessly atop a slender 1.8mm band with a concealed halo beneath the central basket.',
    priceUSD: 8500,
    comparePriceUSD: 9800,
    currency: 'USD',
    
    metalType: 'Yellow Gold',
    purity: '18K',
    goldKarat: '18 Karat (750/1000 Fine Gold)',
    metalColor: 'Royal Yellow Gold',
    grossWeightGrams: 4.8,
    netGoldWeightGrams: 4.3,
    hallmarkAssayOffice: 'Paris Assay Office Eagle Head Hallmark & Maison Aurelia Atelier Mark',
    dimensions: 'Band width: 1.8mm | Setting: 10.5mm x 7.2mm',
    finish: 'High Mirror Polish',
    
    stoneType: 'Natural Diamond',
    stoneWeightCarats: 2.50,
    totalCaratWeight: 2.65,
    gemstoneDetails: {
      type: 'Natural Diamond',
      quantity: 1,
      totalWeightCarats: 2.50,
      treatment: 'None / Untreated',
      dimensionsMm: '10.5 x 7.2 x 4.6 mm',
    },
    certification: {
      issuer: 'GIA',
      certificateNumber: 'GIA-2184910482',
      reportUrl: 'https://www.gia.edu/report-check',
      shape: 'Oval',
      caratWeight: 2.50,
      colorGrade: 'E',
      clarityGrade: 'VVS1',
      cutGrade: 'Excellent',
      polish: 'Excellent',
      symmetry: 'Excellent',
      fluorescence: 'None',
      laserInscription: 'GIA 2184910482',
      certifiedDate: '2025-11-14',
    },
    
    availableSizes: ['US 4.5', 'US 5.0', 'US 5.5', 'US 6.0', 'US 6.5', 'US 7.0', 'US 7.5', 'US 8.0'],
    isCustomizable: true,
    isEngravingAvailable: true,
    maxEngravingChars: 24,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 2,
    estimatedDispatchHours: 24,
    stock: 7,
    lowStockThreshold: 2,
    countryOfOrigin: 'France (Paris Place Vendôme Atelier)',
    status: 'active',
    
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.95,
    reviewCount: 38,
    warrantyPeriodYears: 5,
    careInstructions: 'Clean gently using warm water, mild soap, and a soft-bristled brush. Store in the complimentary suede jewel box.',
    shippingInformation: 'Complimentary insured worldwide courier (Ferrari Group / FedEx Priority). Requires direct signature upon delivery.',
    returnEligibility: 'Eligible for 30-day worldwide complimentary return with original security tag and GIA diamond certificate.',
    exchangeEligibility: 'Lifetime trade-up privilege for natural diamonds of equal or greater value.',
    
    images: [
      {
        id: 'img-1-1',
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
        alt: 'L’Éternité Oval Diamond Solitaire Ring in 18K Yellow Gold',
        type: 'main',
        sortOrder: 1,
      },
      {
        id: 'img-1-2',
        url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=1200&q=85',
        alt: 'Side view showing hidden diamond basket',
        type: 'gallery',
        sortOrder: 2,
      },
      {
        id: 'img-1-3',
        url: 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?auto=format&fit=crop&w=1200&q=85',
        alt: 'Model hand wearing the oval diamond ring',
        type: 'lifestyle',
        sortOrder: 3,
      },
    ],
    variants: [
      { id: 'var-1-1', sku: 'AUR-RNG-001-YG-6', metalType: 'Yellow Gold', purity: '18K', size: 'US 6.0', stoneType: 'Natural Diamond', priceUSD: 8500, stock: 3, isReadyToShip: true },
      { id: 'var-1-2', sku: 'AUR-RNG-001-YG-7', metalType: 'Yellow Gold', purity: '18K', size: 'US 7.0', stoneType: 'Natural Diamond', priceUSD: 8500, stock: 2, isReadyToShip: true },
      { id: 'var-1-3', sku: 'AUR-RNG-001-WG-6', metalType: 'White Gold', purity: '18K', size: 'US 6.0', stoneType: 'Natural Diamond', priceUSD: 8650, stock: 1, isReadyToShip: true },
      { id: 'var-1-4', sku: 'AUR-RNG-001-PT-6', metalType: 'Platinum', purity: '950 Platinum', size: 'US 6.0', stoneType: 'Natural Diamond', priceUSD: 9100, stock: 1, isReadyToShip: false, leadTimeDays: 7 },
    ],
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2026-02-10T14:30:00Z',
  },
  {
    id: 'prod-02',
    name: 'Sovereign Colombian Emerald & Diamond Collar',
    slug: 'sovereign-colombian-emerald-diamond-collar',
    sku: 'AUR-NCK-002',
    brand: 'Maison Aurelia',
    category: 'Necklaces',
    subcategory: 'High Jewellery Collars',
    collection: 'The Royal Emerald Collection',
    gender: 'Women',
    shortDescription: '18.4 carats of certified Muzo emeralds articulated with graduated F/VVS diamond clusters in solid 18K gold.',
    description: 'An opus of Haute Joaillerie craftsmanship. Hand-articulated in 18K solid yellow gold and platinum prongs, the Sovereign Collar drapes like silk across the décolletage. Seven octagonal step-cut Colombian emeralds glow with intense saturation, interspersed with over 450 pavé-set round brilliant diamonds.',
    priceUSD: 24500,
    comparePriceUSD: 28000,
    currency: 'USD',
    
    metalType: 'Yellow Gold',
    purity: '18K',
    goldKarat: '18 Karat (750/1000 Gold + 950 Platinum Bezel)',
    grossWeightGrams: 42.6,
    netGoldWeightGrams: 38.9,
    hallmarkAssayOffice: 'French Customs & Paris Assay Office Hallmark',
    dimensions: 'Length: 16.5 inches (42cm) articulated',
    finish: 'High Mirror Polish',
    
    stoneType: 'Emerald',
    stoneWeightCarats: 18.4,
    totalCaratWeight: 24.8,
    gemstoneDetails: {
      type: 'Emerald',
      variety: 'Muzo Colombian Emerald (Intense Green)',
      quantity: 7,
      totalWeightCarats: 18.4,
      origin: 'Muzo Mines, Boyacá, Colombia',
      treatment: 'Traditional Minor Cedar Oil',
      dimensionsMm: 'Largest 12.0 x 9.5 mm',
    },
    certification: {
      issuer: 'GIA',
      certificateNumber: 'GIA-EM-6819302',
      reportUrl: 'https://www.gia.edu/report-check',
      shape: 'Emerald Cut',
      caratWeight: 18.4,
      colorGrade: 'Fancy Vivid',
      clarityGrade: 'VVS2',
      certifiedDate: '2025-10-08',
    },
    
    chainLengths: ['16.5 inch (42cm)', '18 inch (45cm) with Atelier Extender'],
    isCustomizable: true,
    isEngravingAvailable: true,
    maxEngravingChars: 30,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 3,
    estimatedDispatchHours: 48,
    stock: 2,
    lowStockThreshold: 1,
    countryOfOrigin: 'France (Paris Atelier)',
    status: 'active',
    
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 5.0,
    reviewCount: 12,
    warrantyPeriodYears: 10,
    careInstructions: 'Emeralds are precious natural gems. Avoid ultrasonic cleaners and steam. Clean with a dry microfiber cloth.',
    shippingInformation: 'Hand-delivered via insured armored courier with dedicated concierge handover upon request.',
    returnEligibility: 'Special high-jewellery 14-day inspection and return window with gemological report.',
    exchangeEligibility: 'Guaranteed lifetime valuation and exchange privilege.',
    
    images: [
      {
        id: 'img-2-1',
        url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=85',
        alt: 'Sovereign Colombian Emerald & Diamond Collar Necklace',
        type: 'main',
        sortOrder: 1,
      },
      {
        id: 'img-2-2',
        url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=85',
        alt: 'Emerald detail showing Muzo verdant color',
        type: 'gallery',
        sortOrder: 2,
      },
    ],
    variants: [
      { id: 'var-2-1', sku: 'AUR-NCK-002-YG-16', metalType: 'Yellow Gold', purity: '18K', size: '16.5 inch', stoneType: 'Emerald', priceUSD: 24500, stock: 2, isReadyToShip: true },
    ],
    createdAt: '2025-02-01T10:00:00Z',
    updatedAt: '2026-02-14T11:20:00Z',
  },
  {
    id: 'prod-03',
    name: 'Lumière Riviera Diamond Tennis Bracelet',
    slug: 'lumiere-riviera-diamond-tennis-bracelet',
    sku: 'AUR-BRC-003',
    brand: 'Maison Aurelia',
    category: 'Bracelets',
    subcategory: 'Diamond Tennis Bracelets',
    collection: 'Luminary Diamond Line',
    gender: 'Women',
    shortDescription: '8.00ct total weight of perfectly matched F/VS1 round brilliant diamonds in 18K white gold four-prong setting.',
    description: 'An enduring icon of effortless elegance. Each diamond is individually laser-measured to ensure optical harmony, setting 54 diamonds in seamless articulated links that fluidly trace the wrist. Features a double-safety concealed clasp.',
    priceUSD: 6200,
    comparePriceUSD: 7500,
    currency: 'USD',
    
    metalType: 'White Gold',
    purity: '18K',
    goldKarat: '18 Karat (750 White Gold)',
    grossWeightGrams: 14.2,
    netGoldWeightGrams: 12.6,
    hallmarkAssayOffice: 'Paris Assay Office Hallmark',
    dimensions: 'Length: 7.0 inches (17.8cm) | Width: 3.4mm',
    finish: 'High Mirror Polish',
    
    stoneType: 'Natural Diamond',
    stoneWeightCarats: 8.00,
    totalCaratWeight: 8.00,
    gemstoneDetails: {
      type: 'Natural Diamond',
      quantity: 54,
      totalWeightCarats: 8.00,
      treatment: 'None / Untreated',
    },
    certification: {
      issuer: 'IGI',
      certificateNumber: 'IGI-49201934',
      reportUrl: 'https://www.igi.org/verify-your-report',
      shape: 'Round Brilliant',
      caratWeight: 8.00,
      colorGrade: 'F',
      clarityGrade: 'VS1',
      cutGrade: 'Ideal',
      certifiedDate: '2025-12-01',
    },
    
    availableSizes: ['6.5 inch (16.5cm)', '7.0 inch (17.8cm)', '7.5 inch (19.0cm)'],
    isCustomizable: true,
    isEngravingAvailable: true,
    maxEngravingChars: 12,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 2,
    estimatedDispatchHours: 24,
    stock: 12,
    lowStockThreshold: 3,
    countryOfOrigin: 'France (Paris Atelier)',
    status: 'active',
    
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 44,
    warrantyPeriodYears: 5,
    careInstructions: 'Check prongs annually with an authorized jeweller. Clean with warm soapy water.',
    shippingInformation: 'Complimentary priority worldwide air shipping with full transit insurance.',
    returnEligibility: '30-day global returns with unworn security tag intact.',
    exchangeEligibility: 'Exchangeable within 30 days for alternative length or metal tone.',
    
    images: [
      {
        id: 'img-3-1',
        url: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=1200&q=85',
        alt: 'Lumière Riviera Diamond Tennis Bracelet in 18K White Gold',
        type: 'main',
        sortOrder: 1,
      },
    ],
    variants: [
      { id: 'var-3-1', sku: 'AUR-BRC-003-WG-7', metalType: 'White Gold', purity: '18K', size: '7.0 inch', stoneType: 'Natural Diamond', priceUSD: 6200, stock: 6, isReadyToShip: true },
      { id: 'var-3-2', sku: 'AUR-BRC-003-YG-7', metalType: 'Yellow Gold', purity: '18K', size: '7.0 inch', stoneType: 'Natural Diamond', priceUSD: 6200, stock: 4, isReadyToShip: true },
      { id: 'var-3-3', sku: 'AUR-BRC-003-PT-7', metalType: 'Platinum', purity: '950 Platinum', size: '7.0 inch', stoneType: 'Natural Diamond', priceUSD: 7100, stock: 2, isReadyToShip: true },
    ],
    createdAt: '2025-01-20T10:00:00Z',
    updatedAt: '2026-02-12T16:00:00Z',
  },
  {
    id: 'prod-04',
    name: 'Aurelia Empress 22K Solid Gold Filigree Bangle',
    slug: 'aurelia-empress-22k-solid-gold-filigree-bangle',
    sku: 'AUR-BNG-004',
    brand: 'Maison Aurelia',
    category: 'Bangles',
    subcategory: 'Solid Gold Bangles',
    collection: 'Place Vendôme Heritage',
    gender: 'Women',
    shortDescription: 'Substantial 38-gram solid 22K yellow gold bangle with micro-filigree floral engraving and invisible safety lock.',
    description: 'Forged from deep-tone 22K pure gold alloy (916/1000 fine gold), the Empress Bangle celebrates timeless heirloom artistry. Each filigree motif is hand-carved by master engravers over 40 intensive studio hours.',
    priceUSD: 4950,
    comparePriceUSD: 5600,
    currency: 'USD',
    
    metalType: 'Yellow Gold',
    purity: '22K',
    goldKarat: '22 Karat (916/1000 High Purity Gold)',
    grossWeightGrams: 38.4,
    netGoldWeightGrams: 38.4,
    hallmarkAssayOffice: 'Bureau of Hallmarking Guarantee Stamp 916',
    dimensions: 'Inner Diameter: 60mm (Size 2.6) | Width: 12mm',
    finish: 'Florentine Textured & Polished Filigree',
    
    stoneType: 'None',
    
    availableSizes: ['2.4 (57.2mm)', '2.6 (60.3mm)', '2.8 (63.5mm)'],
    isCustomizable: true,
    isEngravingAvailable: true,
    maxEngravingChars: 20,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 2,
    estimatedDispatchHours: 24,
    stock: 5,
    lowStockThreshold: 1,
    countryOfOrigin: 'France (Place Vendôme)',
    status: 'active',
    
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    rating: 4.98,
    reviewCount: 29,
    warrantyPeriodYears: 10,
    careInstructions: 'Store individually in soft pouch to avoid scratching against other jewellery pieces.',
    shippingInformation: 'Armored direct delivery with Lloyd’s of London comprehensive insurance coverage.',
    returnEligibility: '30-day returns with unbroken hallmark authenticity seal.',
    exchangeEligibility: 'Eligible for lifetime gold bullion weight exchange.',
    
    images: [
      {
        id: 'img-4-1',
        url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=85',
        alt: 'Aurelia Empress 22K Solid Gold Filigree Bangle',
        type: 'main',
        sortOrder: 1,
      },
    ],
    variants: [
      { id: 'var-4-1', sku: 'AUR-BNG-004-26', metalType: 'Yellow Gold', purity: '22K', size: '2.6 (60.3mm)', stoneType: 'None', priceUSD: 4950, stock: 3, isReadyToShip: true },
      { id: 'var-4-2', sku: 'AUR-BNG-004-28', metalType: 'Yellow Gold', purity: '22K', size: '2.8 (63.5mm)', stoneType: 'None', priceUSD: 5200, stock: 2, isReadyToShip: true },
    ],
    createdAt: '2025-01-10T10:00:00Z',
    updatedAt: '2026-02-05T09:00:00Z',
  },
  {
    id: 'prod-05',
    name: 'Archon Platinum & Diamond Men’s Signet Ring',
    slug: 'archon-platinum-diamond-mens-signet-ring',
    sku: 'AUR-MEN-005',
    brand: 'Maison Aurelia',
    category: "Men's Jewellery",
    subcategory: 'Men’s Signet & Statement Rings',
    collection: 'Place Vendôme Heritage',
    gender: 'Men',
    shortDescription: 'Solid 950 platinum signet set with a 1.20ct flush-set step-cut diamond with hand-brushed satin shoulders.',
    description: 'Heirloom substance meets contemporary architectural geometry. The Archon ring is carved from solid forged 950 platinum (24.5 grams), holding a central tension-set step-cut diamond with satin-brushed flanks.',
    priceUSD: 5400,
    comparePriceUSD: 6200,
    currency: 'USD',
    
    metalType: 'Platinum',
    purity: '950 Platinum',
    goldKarat: 'Solid 950 Platinum',
    grossWeightGrams: 24.5,
    netGoldWeightGrams: 0,
    hallmarkAssayOffice: 'French Platinum Assay Hallmark',
    dimensions: 'Top Plate: 14mm x 12mm | Shank: 5mm',
    finish: 'Hand-Brushed Satin with Polished Bevels',
    
    stoneType: 'Natural Diamond',
    stoneWeightCarats: 1.20,
    totalCaratWeight: 1.20,
    certification: {
      issuer: 'GIA',
      certificateNumber: 'GIA-71930281',
      reportUrl: 'https://www.gia.edu/report-check',
      shape: 'Emerald Cut',
      caratWeight: 1.20,
      colorGrade: 'D',
      clarityGrade: 'VVS1',
      cutGrade: 'Excellent',
      certifiedDate: '2025-11-20',
    },
    
    availableSizes: ['US 9.0', 'US 9.5', 'US 10.0', 'US 10.5', 'US 11.0', 'US 12.0'],
    isCustomizable: true,
    isEngravingAvailable: true,
    maxEngravingChars: 16,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 2,
    estimatedDispatchHours: 24,
    stock: 4,
    lowStockThreshold: 1,
    countryOfOrigin: 'France (Paris Atelier)',
    status: 'active',
    
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    rating: 4.96,
    reviewCount: 19,
    warrantyPeriodYears: 10,
    careInstructions: 'Platinum develops a distinguished patina over time. Professional buffing available at any atelier.',
    shippingInformation: 'Dispatched via Ferrari Group Valuables armored carrier.',
    returnEligibility: '30-day complimentary return with GIA certificate dossier.',
    exchangeEligibility: 'Complimentary one-time ring resizing within 90 days.',
    
    images: [
      {
        id: 'img-5-1',
        url: 'https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?auto=format&fit=crop&w=1200&q=85',
        alt: 'Archon Platinum & Diamond Men’s Signet Ring',
        type: 'main',
        sortOrder: 1,
      },
    ],
    variants: [
      { id: 'var-5-1', sku: 'AUR-MEN-005-PT-10', metalType: 'Platinum', purity: '950 Platinum', size: 'US 10.0', stoneType: 'Natural Diamond', priceUSD: 5400, stock: 2, isReadyToShip: true },
      { id: 'var-5-2', sku: 'AUR-MEN-005-YG-10', metalType: 'Yellow Gold', purity: '18K', size: 'US 10.0', stoneType: 'Natural Diamond', priceUSD: 4800, stock: 2, isReadyToShip: true },
    ],
    createdAt: '2025-01-25T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'prod-06',
    name: 'Constellation Burmese Ruby & Diamond Chandelier Earrings',
    slug: 'constellation-burmese-ruby-diamond-chandelier-earrings',
    sku: 'AUR-EAR-006',
    brand: 'Maison Aurelia',
    category: 'Earrings',
    subcategory: 'High Jewellery Drop Earrings',
    collection: 'Solitaire Masterpieces',
    gender: 'Women',
    shortDescription: 'Pair of unheated Burmese pigeon-blood rubies (5.60ctw) suspended from articulated diamond cascading vines.',
    description: 'A tribute to nocturnal glamour. Two certified unheated Burmese rubies exhibiting vibrant fluorescence dangle with articulated freedom beneath marquise and brilliant cut diamonds set in 18K white gold.',
    priceUSD: 16800,
    comparePriceUSD: 19500,
    currency: 'USD',
    
    metalType: 'White Gold',
    purity: '18K',
    goldKarat: '18 Karat White Gold',
    grossWeightGrams: 16.8,
    netGoldWeightGrams: 14.5,
    hallmarkAssayOffice: 'Paris Assay Office Hallmark',
    dimensions: 'Drop Length: 48mm | Width: 14mm',
    finish: 'High Mirror Polish',
    
    stoneType: 'Ruby',
    stoneWeightCarats: 5.60,
    totalCaratWeight: 9.80,
    gemstoneDetails: {
      type: 'Ruby',
      variety: 'Burmese Pigeon Blood Ruby',
      quantity: 2,
      totalWeightCarats: 5.60,
      origin: 'Mogok, Myanmar (Burma)',
      treatment: 'None / Untreated',
    },
    certification: {
      issuer: 'GIA',
      certificateNumber: 'GIA-RB-8920194',
      reportUrl: 'https://www.gia.edu/report-check',
      shape: 'Pear',
      caratWeight: 5.60,
      colorGrade: 'Fancy Vivid',
      clarityGrade: 'VVS2',
      certifiedDate: '2025-11-10',
    },
    
    isCustomizable: true,
    isEngravingAvailable: false,
    
    isReadyToShip: true,
    isMadeToOrder: false,
    productionLeadTimeDays: 2,
    estimatedDispatchHours: 24,
    stock: 2,
    lowStockThreshold: 1,
    countryOfOrigin: 'France (Paris Atelier)',
    status: 'active',
    
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    rating: 5.0,
    reviewCount: 8,
    warrantyPeriodYears: 10,
    careInstructions: 'Wipe with damp cloth after wear. Avoid harsh perfumes or chemical exposure.',
    shippingInformation: 'Complimentary armored delivery with tamper-proof security container.',
    returnEligibility: '14-day high-jewellery return period with accompanying gemological certificates.',
    exchangeEligibility: 'Lifetime exchange privilege towards higher gemstone suites.',
    
    images: [
      {
        id: 'img-6-1',
        url: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1200&q=85',
        alt: 'Constellation Burmese Ruby & Diamond Chandelier Earrings',
        type: 'main',
        sortOrder: 1,
      },
    ],
    variants: [
      { id: 'var-6-1', sku: 'AUR-EAR-006-WG', metalType: 'White Gold', purity: '18K', stoneType: 'Ruby', priceUSD: 16800, stock: 2, isReadyToShip: true },
    ],
    createdAt: '2025-02-05T10:00:00Z',
    updatedAt: '2026-02-16T12:00:00Z',
  },
];

export const mockShippingMethods: ShippingMethodOption[] = ARMORED_SHIPPING_METHODS;

export const mockCoupons: Coupon[] = [
  {
    code: 'MAISON10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderUSD: 3000,
    expiryDate: '2027-12-31T23:59:59Z',
    isActive: true,
    description: '10% privilege courtesy on acquisitions over $3,000',
  },
  {
    code: 'VENDOME500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderUSD: 5000,
    expiryDate: '2027-12-31T23:59:59Z',
    isActive: true,
    description: '$500 Atelier welcome credit for new patrons',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev-01',
    productId: 'prod-01',
    userName: 'Geneviève de Saint-Germain',
    userCountry: 'France',
    rating: 5,
    title: 'The oval diamond is utterly incandescent',
    comment: 'The fire and optical dispersion of this 2.50ct solitaire exceeded every expectation. The hidden diamond gallery under the basket is an exquisite subtle detail that reveals itself only upon close inspection.',
    isVerifiedBuyer: true,
    verifiedPieceName: 'L’Éternité Oval Diamond Solitaire Ring (18K Gold)',
    createdAt: '2026-01-20T14:22:00Z',
  },
  {
    id: 'rev-02',
    productId: 'prod-02',
    userName: 'Lord Alistair Sterling',
    userCountry: 'United Kingdom',
    rating: 5,
    title: 'An heirloom worthy of a national museum collection',
    comment: 'The saturated green of these Muzo emeralds is legendary. Hand delivery via Ferrari Group armored service to Mayfair was punctual, discreet, and thoroughly reassuring.',
    isVerifiedBuyer: true,
    verifiedPieceName: 'Sovereign Colombian Emerald & Diamond Collar',
    createdAt: '2026-02-02T18:45:00Z',
  },
  {
    id: 'rev-03',
    productId: 'prod-03',
    userName: 'Sophia Montgomery-Vance',
    userCountry: 'United States',
    rating: 5,
    title: 'Flawless diamond rhythm and sublime weight',
    comment: 'The articulation of the bracelet is seamless; it rolls across the wrist like liquid silk. The IGI grading documents were sealed with wax in a leather folder. Truly bespoke luxury.',
    isVerifiedBuyer: true,
    verifiedPieceName: 'Lumière Riviera Diamond Tennis Bracelet',
    createdAt: '2026-02-08T09:12:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: 'usr-admin-01',
    name: 'Director Jean-Paul Laurent',
    email: 'admin@aureliajewels.com',
    role: 'superadmin',
    phone: '+33 1 42 68 00 00',
    country: 'France',
    addresses: [
      {
        firstName: 'Jean-Paul',
        lastName: 'Laurent',
        email: 'admin@aureliajewels.com',
        phone: '+33 1 42 68 00 00',
        addressLine1: '12 Place Vendôme',
        city: 'Paris',
        stateOrProvince: 'Île-de-France',
        postalCode: '75001',
        country: 'France',
        countryCode: 'FR',
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'usr-client-01',
    name: 'Elena Rostova',
    email: 'patron@domain.com',
    role: 'customer',
    phone: '+1 212 555 0199',
    country: 'United States',
    addresses: [
      {
        firstName: 'Elena',
        lastName: 'Rostova',
        email: 'patron@domain.com',
        phone: '+1 212 555 0199',
        addressLine1: '740 Park Avenue',
        addressLine2: 'Apt 14B',
        city: 'New York',
        stateOrProvince: 'NY',
        postalCode: '10021',
        country: 'United States',
        countryCode: 'US',
      },
    ],
    createdAt: '2025-06-15T12:00:00Z',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-2026-081',
    orderNumber: 'AUR-2026-0081',
    userId: 'usr-client-01',
    customerEmail: 'patron@domain.com',
    customerPhone: '+1 212 555 0199',
    shippingAddress: {
      firstName: 'Elena',
      lastName: 'Rostova',
      email: 'patron@domain.com',
      phone: '+1 212 555 0199',
      addressLine1: '740 Park Avenue',
      addressLine2: 'Apt 14B',
      city: 'New York',
      stateOrProvince: 'NY',
      postalCode: '10021',
      country: 'United States',
      countryCode: 'US',
    },
    items: [
      {
        productId: 'prod-01',
        variantId: 'var-1-1',
        sku: 'AUR-RNG-001-YG-6',
        name: 'L’Éternité Oval Diamond Solitaire Ring',
        slug: 'leternite-oval-diamond-solitaire-ring',
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=85',
        metalType: 'Yellow Gold',
        purity: '18K',
        size: 'US 6.0',
        stoneType: 'Natural Diamond',
        engravingText: 'Pour Toujours • E & V',
        certificateNumber: 'GIA-2184910482',
        unitPriceUSD: 8500,
        quantity: 1,
        totalUSD: 8500,
      },
    ],
    subtotalUSD: 8500,
    discountUSD: 500,
    couponCode: 'VENDOME500',
    shippingCostUSD: 0,
    taxCostUSD: 560,
    customsDutyCostUSD: 0,
    totalUSD: 8560,
    currency: 'USD',
    totalInCurrency: 8560,
    exchangeRateUsed: 1.0,
    shippingMethodId: 'ship-ferrari-valuable',
    shippingMethodName: 'Ferrari Group International Valuables Courier',
    carrierName: 'Ferrari Group Valuables',
    trackingNumber: 'FG-VAL-2026-98104',
    trackingUrl: 'https://www.ferrarigroup.net',
    insurancePolicyNumber: 'LLOYDS-VENDOME-882914',
    status: 'in_transit',
    paymentStatus: 'paid',
    paymentMethod: 'stripe',
    paymentIntentId: 'pi_3P92k8AureliaJewelsLive',
    notes: 'Engraving verified by Master Hand Engraver. Tamper-evident wax seal intact.',
    createdAt: '2026-02-18T10:15:00Z',
    updatedAt: '2026-02-19T08:30:00Z',
    estimatedDeliveryDate: '2026-02-22T17:00:00Z',
  },
];

export const mockBespokeInquiries: BespokeInquiry[] = [
  {
    id: 'bespoke-001',
    referenceNumber: 'BESPOKE-2026-001',
    customerName: 'Countess Camille d’Orsay',
    customerEmail: 'camille.dorsay@domain.fr',
    customerPhone: '+33 6 12 34 56 78',
    customerCountry: 'France',
    category: 'Rings',
    metalPreference: 'Platinum',
    purityPreference: '950 Platinum',
    stonePreference: 'Natural Diamond',
    targetCarat: 4.5,
    targetBudgetUSD: '$35,000 - $50,000',
    sizeSpecification: 'EU 52 (US 6)',
    engravingMessage: 'C & A • 2026',
    designDescription: 'Art Deco architectural emerald-cut diamond ring flanked by tapered baguette diamonds with micro-milgrain edges.',
    timelineRequirement: 'Within 4 weeks for wedding anniversary celebration.',
    status: 'cad_in_progress',
    createdAt: '2026-02-14T11:00:00Z',
  },
];

export const mockStaff: AtelierStaff[] = [
  {
    id: 'stf-01',
    name: 'Jean-Paul Laurent',
    email: 'admin@aureliajewels.com',
    role: 'SUPER_ADMIN',
    specialty: 'Executive Haute Joaillerie Director',
    activeTicketsCount: 3,
  },
  {
    id: 'stf-02',
    name: 'Master Goldsmith Henri Vane',
    email: 'henri.vane@aureliajewels.com',
    role: 'MASTER_JEWELLER',
    specialty: 'High Jewelry Forging & Platinum Filigree',
    activeTicketsCount: 4,
  },
  {
    id: 'stf-03',
    name: 'Dr. Vivienne Moreau, GG',
    email: 'vivienne.moreau@aureliajewels.com',
    role: 'SENIOR_GEMOLOGIST',
    specialty: 'GIA Diamond & Colored Gemstone Sourcing',
    activeTicketsCount: 2,
  },
  {
    id: 'stf-04',
    name: 'Claire de Montmirail',
    email: 'claire.montmirail@aureliajewels.com',
    role: 'ATELIER_STAFF',
    specialty: 'VIP Patron Relations & Armored Dispatch',
    activeTicketsCount: 5,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    ticketNumber: 'AUR-CHAT-84920',
    userId: 'usr-client-01',
    userName: 'Elena Rostova',
    userEmail: 'patron@domain.com',
    userPhone: '+1 (212) 555-0199',
    subject: 'Aethel Solitaire Ring — Platinum 950 Setting & Custom Laser Engraving',
    type: 'product_modification',
    status: 'IN_PROGRESS',
    priority: 'high',
    productId: 'prod-01',
    productContext: {
      productId: 'prod-01',
      productName: 'The Aethel Solitaire Diamond Ring',
      productSlug: 'aethel-solitaire-diamond-ring',
      sku: 'AUR-RNG-001',
      image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
      priceUSD: 8500,
      selectedMetal: 'Platinum',
      selectedPurity: '950 Platinum',
      selectedSize: 'US 6.5',
      selectedStone: 'Natural Diamond (2.20 ct D-IF)',
      engravingRequested: 'Eternally Yours • 2026',
    },
    assignedStaffId: 'stf-02',
    assignedStaffName: 'Master Goldsmith Henri Vane',
    internalNotes: 'Client requests bespoke platinum prongs with hidden emerald pavilion accent. CAD rendering prepared for review.',
    unreadByUserCount: 1,
    unreadByAdminCount: 0,
    createdAt: '2026-02-18T14:20:00Z',
    updatedAt: '2026-02-19T09:45:00Z',
    messages: [
      {
        id: 'msg-001-1',
        conversationId: 'conv-001',
        senderId: 'usr-client-01',
        senderName: 'Elena Rostova',
        senderRole: 'customer',
        content: 'Greetings. I am acquiring The Aethel Solitaire Diamond Ring, but I would like to request the band crafted in Solid 950 Platinum rather than 18K Yellow Gold, along with the custom engraving "Eternally Yours • 2026". Can you confirm the lead time?',
        createdAt: '2026-02-18T14:20:00Z',
        isReadByRecipient: true,
      },
      {
        id: 'msg-001-2',
        conversationId: 'conv-001',
        senderId: 'stf-02',
        senderName: 'Master Goldsmith Henri Vane',
        senderRole: 'master_jeweller',
        content: 'Good afternoon Madame Rostova. It is our absolute pleasure to assist you. Crafting The Aethel in hand-forged 950 Platinum with hand-engraved French cursive will take approximately 8 business days at our Paris Place Vendôme atelier. We have reserved a flawless D-Color Triple Excellent GIA diamond for your piece. Would you like a complimentary hidden 0.05ct sapphire flush-set inside the bridge?',
        createdAt: '2026-02-18T16:05:00Z',
        isReadByRecipient: true,
      },
      {
        id: 'msg-001-3',
        conversationId: 'conv-001',
        senderId: 'usr-client-01',
        senderName: 'Elena Rostova',
        senderRole: 'customer',
        content: 'That would be exquisite! Please proceed with the hidden sapphire. I have authorized the acquisition bag.',
        createdAt: '2026-02-19T09:15:00Z',
        isReadByRecipient: true,
      },
      {
        id: 'msg-001-4',
        conversationId: 'conv-001',
        senderId: 'stf-02',
        senderName: 'Master Goldsmith Henri Vane',
        senderRole: 'master_jeweller',
        content: 'Splendid. The atelier CAD bench has generated the technical rendering attached below. Your order status is active and will be dispatched under insured Ferrari Group security courier.',
        createdAt: '2026-02-19T09:45:00Z',
        attachments: [
          {
            id: 'att-01',
            name: 'Aethel_Platinum_CAD_Technical_Dossier.pdf',
            url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
            type: 'cad_drawing',
          },
        ],
        isReadByRecipient: false,
      },
    ],
  },
  {
    id: 'conv-002',
    ticketNumber: 'AUR-CHAT-91823',
    userId: 'usr-client-01',
    userName: 'Elena Rostova',
    userEmail: 'patron@domain.com',
    userPhone: '+1 (212) 555-0199',
    subject: 'Order #AUR-2026-0081 — Ferrari Group Armored Delivery Window',
    type: 'order_inquiry',
    status: 'OPEN',
    priority: 'medium',
    orderId: 'ord-2026-081',
    orderContext: {
      orderId: 'ord-2026-081',
      orderNumber: 'AUR-2026-0081',
      orderTotalUSD: 8560,
      orderDate: '2026-02-18',
      status: 'in_transit',
      trackingNumber: 'FG-VAL-2026-98104',
    },
    assignedStaffId: 'stf-04',
    assignedStaffName: 'Claire de Montmirail',
    internalNotes: 'Consignment is in armored transit via Ferrari Group Zurich-New York route. Delivery scheduled for Feb 22.',
    unreadByUserCount: 0,
    unreadByAdminCount: 1,
    createdAt: '2026-02-19T11:00:00Z',
    updatedAt: '2026-02-19T11:00:00Z',
    messages: [
      {
        id: 'msg-002-1',
        conversationId: 'conv-002',
        senderId: 'usr-client-01',
        senderName: 'Elena Rostova',
        senderRole: 'customer',
        content: 'Hello, could you please confirm the exact delivery hour window for consignment #AUR-2026-0081 arriving in Manhattan? I wish to ensure my building concierge and private security are present.',
        createdAt: '2026-02-19T11:00:00Z',
        isReadByRecipient: false,
      },
    ],
  },
];

